title: Swetasudha Panda
author:
  name: "Swetasudha Panda"

# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'Home', path: '.', url: ''}
- {name: 'Publications', path: 'menu', url: 'publications.html'}
# - {name: 'Contact', path: 'menu', url: 'contact.html'}
#menu:
#- {name: 'Home', path: 'menu', url: 'home.html'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'github', link: 'https://www.github.com/swetapanda'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'dblp', link: 'https://dblp.org/pid/161/0025.html'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/swetasudhapanda/'}
- {icon: 'envelope', link: 'mailto:swetasudhaiitkgp@gmail.com'}
- {icon: 'book', link: 'https://dblp.org/pid/161/0025.html'}
- {icon: 'map-marker-alt', link: 'https://www.google.com/maps/place/Boston,+MA/@42.3140089,-71.2504676,10z/data=!3m1!4b1!4m5!3m4!1s0x89e3652d0d3d311b:0x787cbf240162e8a0!8m2!3d42.3600825!4d-71.0588801'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

# sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy:'

# post_date_prefix: 'Written on'
